# Generated by Django 3.1.8 on 2021-05-29 13:34

import attendance_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(default='0')),
                ('profile_path', models.ImageField(blank=True, upload_to=attendance_system.models.student_directory_path)),
            ],
        ),
    ]
