# Generated by Django 3.1.8 on 2021-05-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0002_auto_20210529_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('未签到', '未签到'), ('已签到', '已签到')], default='未签到', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
